name: mioflow
dependencies:
  - pot
  - phate
  - scprep
  - graphtools
  - pandas
  - argparse
  - matplotlib
  - numpy
  - scikit-learn
  - scipy
  - pytorch
  - cudatoolkit=11.3
  - torchdiffeq
  - ipykernel
  - seaborn
  - matplotlib
  - tqdm
  - yaml
  - ipython
  - ipywidgets
  # - jupyterlab
  # - jupyter_contrib_nbextensions
  # - nb_conda_kernels
channels:
  - conda-forge
  - pytorch
  - bioconda