input_dim: 2
output_dim: 50
layer_widths:
- 32
- 32
dropout: 0.1
batchnorm: true
weight_decay: 0.0001
lr: 0.001
weighted_loss: true
scheduler:
  name: reduce_on_plateau
  patience: 5
  factor: 0.5
  min_lr: 1.0e-06
  monitor: decoder/val_loss
metric_prefix: decoder/
