# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MIOFlow/',
                'doc_host': 'https://KrishnaswamyLab.github.io',
                'git_url': 'https://github.com/KrishnaswamyLab/MIOFlow/tree/main/',
                'lib_path': 'MIOFlow'},
  'syms': { 'MIOFlow.constants': {},
            'MIOFlow.datasets': {},
            'MIOFlow.eval': {},
            'MIOFlow.exp': {},
            'MIOFlow.geo': {},
            'MIOFlow.losses': {},
            'MIOFlow.models': {},
            'MIOFlow.ode': {},
            'MIOFlow.plots': {},
            'MIOFlow.train': {},
            'MIOFlow.utils': {}}}